# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20170430_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='OT',
            field=models.CharField(blank=True, choices=[('seldom', '\u5e7e\u4e4e\u4e0d\u52a0\u73ed'), ('sometimes', '\u5076\u723e\u52a0\u73ed'), ('often', '\u7d93\u5e38\u52a0\u73ed'), ('always', '\u5e7e\u4e4e\u6bcf\u5929\u52a0\u73ed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='Overtime_pay',
            field=models.CharField(blank=True, choices=[('yes', '\u6709'), ('no', '\u6c92\u6709'), ('not_sure', '\u4e0d\u77e5\u9053')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='employed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='experience',
            field=models.CharField(blank=True, choices=[('1', '1\u5e74\u6216\u4ee5\u4e0b'), ('2', '2\u5e74\u6216\u4ee5\u4e0b'), ('3', '3\u5e74\u6216\u4ee5\u4e0b')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', '\u7537'), ('female', '\u5973'), ('other', '\u5176\u4ed6')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='types',
            field=models.CharField(blank=True, choices=[('full_time', '\u5168\u8077'), ('part_time', '\u517c\u8077(\u542b\u6253\u5de5)'), ('interm', '\u5be6\u7fd2'), ('temporary', '\u81e8\u6642\u5de5'), ('contract', '\u7d04\u8058\u96c7'), ('deliver', '\u6d3e\u9063')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='working_hour',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
