# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20170430_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='sex',
            field=models.CharField(choices=[('male', '\u7537'), ('female', '\u5973'), ('other', '\u5176\u4ed6')], max_length=100),
        ),
    ]
