# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20170430_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='employed',
            field=models.CharField(blank=True, choices=[('yes', '\u5728\u8077'), ('no', '\u7121\u696d')], max_length=100),
        ),
    ]
