# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20170501_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 29, 14, 32, 26, 415060)),
        ),
    ]
