# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 21:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20170530_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_detail',
            name='salary_type',
            field=models.CharField(choices=[('1', '\u5e74\u85aa'), ('2', '\u6708\u85aa'), ('3', '\u65e5\u85aa'), ('4', '\u6642\u85aa')], default='\u6708\u85aa', max_length=10),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 30, 14, 42, 3, 754006)),
        ),
    ]
