# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 22:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20170530_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='OT',
            field=models.CharField(choices=[('seldom', '\u7d55\u5c11'), ('sometimes', '\u5076\u723e'), ('often', '\u7d93\u5e38'), ('always', '\u5e7e\u4e4e\u6bcf\u5929')], default='seldom', max_length=100),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='Overtime_pay',
            field=models.CharField(choices=[('yes', '\u6709'), ('no', '\u6c92\u6709'), ('not_sure', '\u4e0d\u77e5\u9053')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 17, 15, 7, 15, 15617)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='employed',
            field=models.CharField(blank=True, choices=[('yes', '\u5728\u8077'), ('no', '\u7121\u696d')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='experience',
            field=models.CharField(blank=True, choices=[('0', '\u8acb\u9078\u64c7'), ('1', '1\u5e74\u6216\u4ee5\u4e0b'), ('2', '2\u5e74\u6216\u4ee5\u4e0b'), ('3', '3\u5e74\u6216\u4ee5\u4e0b')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='salary_type',
            field=models.CharField(blank='True', choices=[('0', '\u8acb\u9078\u64c7'), ('1', '\u5e74\u85aa'), ('2', '\u6708\u85aa'), ('3', '\u65e5\u85aa'), ('4', '\u6642\u85aa')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='sex',
            field=models.CharField(blank=True, choices=[('0', '\u8acb\u9078\u64c7'), ('male', '\u7537'), ('female', '\u5973'), ('other', '\u5176\u4ed6')], default='male', max_length=100),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='types',
            field=models.CharField(blank=True, choices=[('full_time', '\u5168\u8077'), ('part_time', '\u517c\u8077(\u542b\u6253\u5de5)'), ('interm', '\u5be6\u7fd2'), ('temporary', '\u81e8\u6642\u5de5'), ('contract', '\u7d04\u8058\u96c7'), ('deliver', '\u6d3e\u9063')], default='full_time', max_length=100),
        ),
    ]
