# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20170617_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 10, 18, 56, 21, 714797)),
        ),
    ]
