# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 02:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20170710_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 10, 19, 25, 4, 414175)),
        ),
    ]
