# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 02:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20170710_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 10, 19, 26, 26, 725768)),
        ),
    ]
