# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 22:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20170710_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 14, 15, 53, 32, 509404)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 14, 15, 53, 32, 510457)),
        ),
    ]
