# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 23:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20170714_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelance',
            name='average',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='freelance',
            name='max_salary',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='freelance',
            name='min_salary',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='freelance',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 14, 16, 40, 39, 834778)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 14, 16, 40, 39, 836047)),
        ),
    ]
